(* EBNF definition of a formula used to compute a metric *)

formula     = expression $ ;

expression  = positive+:term { ("+" positive+:term | "-" negative+:term) } ;

term        = numerator+:factor { ( "*" numerator+:factor | "/" denominator+:factor ) } ;

factor      =
            @:application |
            @:constant |
            @:variable |
            "(" @:expression ")";

application = name:name "(" { arguments+:expression "," } arguments+:expression ")" ;

name        = /[A-Za-z]+/ ;

variable    = /__[0-9]+__/ ;

constant    = /-?[0-9]+(\.[0-9]*)?(e[0-9]+)?/ ;
